### PR TITLE
collaborative e-invoice composition

### PR DESCRIPTION
**Pull request by gsvarovsky**
Draft threat model for Collaborative e-Invoice Composition (CIC).

Readable content is in [threats/e-invoicing.md](https://github.com/m-ld/m-ld-security-spec/blob/e-invoicing/threats/e-invoicing.md) (the other files are includes).

### CODE REVIEW

**Comment by michielbdejong** [comment]
Where can I find [@cicirielloPEPPOLTransportInfrastructure2011], is it https://www.galaxygw.com/wp-content/uploads/openpeppol/20111122-peppol-transport-infrastructure-v1.17.pdf ?

**Comment by michielbdejong** [comment]
The https://vefa.difi.no/iso20022/ link redirects to https://anskaffelser.dev/

**Comment by gsvarovsky** [comment]
> Where can I find [@cicirielloPEPPOLTransportInfrastructure2011]

Sorry, I somehow failed to update the biblio, it's now in [references.bib](https://github.com/m-ld/m-ld-security-spec/blob/e-invoicing/references.bib). Your link is correct!

**Comment by michielbdejong** [comment]
Great read!

What I'm missing is maybe a table of contents (objectives, application profile, application composition, threats), an introduction explaining how those sections fit together, and a conclusion section briefly stating how we can use the information collected here to move forward.

For instance, does this analysis inform feature requests for m-ld? And given the threats overview in section 3, is the application composition described in section 2 any good or is it all one big leaky bucket? Maybe these conclusions are out of scope, but I was left with a need for them after reading the document.

A lot of threats are mentioned (I know this is the purpose of this document) and I'm curious if we could use this analysis to build a system that holds up against these threats. What do you think?

**Comment by gsvarovsky** [comment]
Thanks very much for the review @michielbdejong! The document introduction, motivation and structure are in the [folder README](https://github.com/m-ld/m-ld-security-spec/tree/main/threats), sorry not to have mentioned it. I'll put in an explicit link.

Conclusion is a great idea – be good to tie things up a bit ready for the next step (design) – see also the [project structure](https://github.com/orgs/m-ld/projects/5). I'll do that now.

In general, I want to iterate something like this: design some security controls, try to break it, design some more, can I still break it? I'm not sure it's worth having an explicit first step "can I break it without any controls at all", though doing so might be useful for someone coming to this blind. I'll have a think and suggest something.

**Comment by uvdsl** [comment]
Hi, just some minor comments from my side as I am not too familiar with the writing style expected in thread models.

Terminology:
I am unsure if `real-time` and `live` are the correct terms by definition. AFAIK these terms require and infer very high availability in the corresponding systems which is not quite the case when parties can be offline. But I may be wrong :) Intuitively I would have reverted to `asynchronous and in parallel`.
 
Next, `single logical document` is a very good expression. For the uninformed reader, however, this may be too little context to fully understand the fact that this logical document is `represented by local replicas`. Maybe you could add that. Otherwise it is not clear why there could be different states of the document which you are referring to in the integrity section. If you assume the reader to know about CRDTs, then it's fine.

Diagrams:
Maybe the flow diagram would benefit from the direct inclusion of the key for better readability?
And the deployment diagram has transparent background, except for two subimages (which you can see when in dark mode).

Cheers
Christoph

**Comment by uvdsl** [comment]
Addendum:
Regarding `severity`, you only list `low` and `medium` threads. What would you classify as `high` severity? Is that more a qualitative assessment or is there some specification that defines the different thread levels?
Cheers!

**Comment by gsvarovsky** [comment]
> I am unsure if `real-time` and `live` are the correct terms by definition

I've removed the uses of these terms and added some clarification to the opening. Hopefully it's addressed your second point to some degree too. However, I do think I have to rely on some prior awareness of **m-ld**. Really, the document has these goals:
1. For me to satisfy myself, and a domain specialist who is already up to speed on the ideas, that we understand the domain threats enough to start designing some controls, and
2. To demonstrate I've done my homework.

Thanks for the diagram tips!

> Regarding `severity`, you only list `low` and `medium` threads.

I don't really want to get into a quantitative analysis in this respect – the value of trying is debated – so really this is just a qualitative summary indicator. I've added the word 'indicative'.

**Comment by gsvarovsky** [comment]
> ... you should specify purchase order versus a sales order... https://planergy.com/blog/purchase-order-sales-order/ ... In the ERP systems the PO related to the buyer, while the SO relates to the supplier

> Would delivery without payment be listed on the table in integrity, or no because you could just not deliver until you receive payment...

> confidentiality - 4th paragraph... some other data that might be on the order would it be billing/shipping address details. and maybe that depends on if it's a PO or a SO...

**Review by michielbdejong — APPROVED** [review]
\o/

**Pull request merged**
